//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LFAdminEntities : DbContext
    {
        public LFAdminEntities()
            : base("name=LFAdminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Basic_Data> T_Basic_Data { get; set; }
        public virtual DbSet<T_Role> T_Role { get; set; }
        public virtual DbSet<T_Role_Permission> T_Role_Permission { get; set; }
        public virtual DbSet<T_User> T_User { get; set; }
        public virtual DbSet<T_User_Permission> T_User_Permission { get; set; }
        public virtual DbSet<T_User_Role> T_User_Role { get; set; }
        public virtual DbSet<V_User_Permission> V_User_Permission { get; set; }
        public virtual DbSet<T_Company> T_Company { get; set; }
        public virtual DbSet<T_Department> T_Department { get; set; }
        public virtual DbSet<T_Permission> T_Permission { get; set; }
    }
}
